name: Deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main # Chạy khi có code push vào nhánh main giống dưới máy bạn

env:
  AZURE_WEBAPP_NAME: 'webapp-HaNgocAn' # Tên Web App chuẩn của bạn

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v3

    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '24.x' # Dùng Node 22 chuẩn theo danh sách hỗ trợ của Azure
        cache: 'npm'

    - name: Install dependencies and build
      run: |
        npm install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
