name: Deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main # Chạy tự động khi push vào nhánh main

env:
  AZURE_WEBAPP_NAME: 'webapp-hangocan' # Tên viết thường để khớp hoàn toàn với Publish Profile

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v3

    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '24.x' # Đồng bộ lên Node 24 theo môi trường của bạn
        cache: 'npm'

    - name: Install dependencies and build
      run: |
        npm install

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}